import type { StaffMessageTemplate, StaffTemplateCategory } from '@/types/staff-templates'
import type { InternalMessagePriority, StaffDepartment } from '@/types/messaging'

export const DEFAULT_STAFF_TEMPLATES: Omit<StaffMessageTemplate, 'id' | 'usageCount' | 'isFavorite' | 'isCustom' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Room Ready for Check-In',
    category: 'ROOM_STATUS',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: 'Room {{roomNumber}} has been cleaned and inspected. Status: {{status}}. Ready for check-in.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 101' },
      { key: 'status', label: 'Status', type: 'text', required: true, defaultValue: 'Clean' },
    ],
    requiresAcknowledgment: false,
    tags: ['housekeeping', 'check-in', 'room-ready'],
  },
  {
    name: 'Room Issue - Requires Attention',
    category: 'ROOM_STATUS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'HIGH',
    body: 'Issue found in Room {{roomNumber}}: {{issue}}. Guest checking in at {{checkInTime}}. Please address ASAP.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 101' },
      { key: 'issue', label: 'Issue Description', type: 'text', required: true, placeholder: 'e.g. AC not working' },
      { key: 'checkInTime', label: 'Check-in Time', type: 'time', required: true, placeholder: 'e.g. 3:00 PM' },
    ],
    requiresAcknowledgment: true,
    tags: ['urgent', 'room-issue', 'maintenance-needed'],
  },
  {
    name: 'Room Inspection Failed',
    category: 'ROOM_STATUS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'HIGH',
    body: 'Room {{roomNumber}} failed inspection. Issues: {{issues}}. Please re-clean and notify when ready. Expected arrival: {{arrivalTime}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 203' },
      { key: 'issues', label: 'Issues Found', type: 'text', required: true, placeholder: 'e.g. Bathroom not clean, bed not made' },
      { key: 'arrivalTime', label: 'Expected Arrival', type: 'time', required: true, placeholder: 'e.g. 3:00 PM' },
    ],
    requiresAcknowledgment: true,
    tags: ['inspection', 'failed', 're-clean'],
  },
  {
    name: 'Room Out of Order',
    category: 'ROOM_STATUS',
    targetDepartment: 'ALL',
    priority: 'URGENT',
    body: '🚫 Room {{roomNumber}} is now OUT OF ORDER. Reason: {{reason}}. Expected repair time: {{repairTime}}. Please update availability.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 305' },
      { key: 'reason', label: 'Reason', type: 'text', required: true, placeholder: 'e.g. Plumbing major leak' },
      { key: 'repairTime', label: 'Expected Repair Time', type: 'text', required: false, defaultValue: 'TBD' },
    ],
    requiresAcknowledgment: true,
    tags: ['out-of-order', 'urgent', 'availability'],
  },
  {
    name: 'Room Back in Service',
    category: 'ROOM_STATUS',
    targetDepartment: 'ALL',
    priority: 'HIGH',
    body: '✅ Room {{roomNumber}} is back in service. Repairs completed: {{repairs}}. Room status: {{status}}. Available for booking.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 305' },
      { key: 'repairs', label: 'Repairs Completed', type: 'text', required: true, placeholder: 'e.g. Plumbing fixed, deep clean done' },
      { key: 'status', label: 'Current Status', type: 'text', required: true, defaultValue: 'Clean and ready' },
    ],
    requiresAcknowledgment: false,
    tags: ['back-in-service', 'availability', 'repaired'],
  },
  {
    name: 'Deep Clean Required',
    category: 'ROOM_STATUS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Room {{roomNumber}} requires deep cleaning. Reason: {{reason}}. Schedule for: {{scheduleDate}}. Expected duration: {{duration}} hours.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 410' },
      { key: 'reason', label: 'Reason', type: 'text', required: true, placeholder: 'e.g. Extended stay checkout' },
      { key: 'scheduleDate', label: 'Schedule Date', type: 'date', required: true, placeholder: 'Tomorrow' },
      { key: 'duration', label: 'Duration (hours)', type: 'number', required: false, defaultValue: '4' },
    ],
    requiresAcknowledgment: false,
    tags: ['deep-clean', 'scheduling', 'housekeeping'],
  },
  {
    name: 'Guest Special Request',
    category: 'GUEST_REQUEST',
    targetDepartment: 'ALL',
    priority: 'NORMAL',
    body: 'Guest {{guestName}} in Room {{roomNumber}} has requested: {{request}}. Please fulfill by {{deadline}}.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 101' },
      { key: 'request', label: 'Request Details', type: 'text', required: true, placeholder: 'e.g. Extra towels' },
      { key: 'deadline', label: 'Deadline', type: 'time', required: false, defaultValue: 'ASAP' },
    ],
    requiresAcknowledgment: false,
    tags: ['guest-request', 'service'],
  },
  {
    name: 'VIP Arrival Today',
    category: 'GUEST_REQUEST',
    targetDepartment: 'ALL',
    priority: 'HIGH',
    body: '⭐ VIP Guest arriving today: {{guestName}}, Room {{roomNumber}}. Check-in at {{checkInTime}}. Special requests: {{requests}}. Please ensure exceptional service.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 501' },
      { key: 'checkInTime', label: 'Check-in Time', type: 'time', required: true, placeholder: 'e.g. 2:00 PM' },
      { key: 'requests', label: 'Special Requests', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: true,
    tags: ['vip', 'arrival', 'special-attention'],
  },
  {
    name: 'Extra Amenities Request',
    category: 'GUEST_REQUEST',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Room {{roomNumber}} - Guest {{guestName}} requests extra amenities: {{items}}. Deliver by {{deliverBy}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 208' },
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'items', label: 'Items Requested', type: 'text', required: true, placeholder: 'e.g. 2 pillows, 3 towels' },
      { key: 'deliverBy', label: 'Deliver By', type: 'time', required: false, defaultValue: 'Within 30 minutes' },
    ],
    requiresAcknowledgment: false,
    tags: ['amenities', 'guest-request', 'housekeeping'],
  },
  {
    name: 'Room Service Request',
    category: 'GUEST_REQUEST',
    targetDepartment: 'ALL',
    priority: 'NORMAL',
    body: 'Room service order for Room {{roomNumber}} - {{guestName}}:\n\nOrder: {{orderDetails}}\nDelivery time: {{deliveryTime}}\nSpecial instructions: {{instructions}}',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 312' },
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'orderDetails', label: 'Order Details', type: 'text', required: true, placeholder: 'e.g. 2x breakfast, coffee' },
      { key: 'deliveryTime', label: 'Delivery Time', type: 'time', required: true, placeholder: 'e.g. 8:00 AM' },
      { key: 'instructions', label: 'Special Instructions', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: false,
    tags: ['room-service', 'food', 'guest-request'],
  },
  {
    name: 'Wake-Up Call Request',
    category: 'GUEST_REQUEST',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: 'Wake-up call requested for Room {{roomNumber}} - {{guestName}} at {{wakeUpTime}}. {{additionalNotes}}',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 415' },
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'wakeUpTime', label: 'Wake-Up Time', type: 'time', required: true, placeholder: 'e.g. 6:00 AM' },
      { key: 'additionalNotes', label: 'Additional Notes', type: 'text', required: false, defaultValue: '' },
    ],
    requiresAcknowledgment: false,
    tags: ['wake-up-call', 'guest-request', 'front-desk'],
  },
  {
    name: 'Accessibility Request',
    category: 'GUEST_REQUEST',
    targetDepartment: 'ALL',
    priority: 'HIGH',
    body: 'Guest {{guestName}} in Room {{roomNumber}} requires accessibility accommodations: {{accommodations}}. Please arrange immediately.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 112' },
      { key: 'accommodations', label: 'Accommodations Needed', type: 'text', required: true, placeholder: 'e.g. Shower chair, grab bars check' },
    ],
    requiresAcknowledgment: true,
    tags: ['accessibility', 'guest-request', 'priority'],
  },
  {
    name: 'Do Not Disturb - Extended',
    category: 'GUEST_REQUEST',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Room {{roomNumber}} - Guest has placed DND for {{duration}}. No service until {{serviceAfter}}. Monitor for towel/supply needs.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 520' },
      { key: 'duration', label: 'Duration', type: 'text', required: true, placeholder: 'e.g. 48 hours' },
      { key: 'serviceAfter', label: 'Service After', type: 'date', required: true, placeholder: 'e.g. Tomorrow 2PM' },
    ],
    requiresAcknowledgment: false,
    tags: ['dnd', 'housekeeping', 'guest-preference'],
  },
  {
    name: 'Maintenance Request - Urgent',
    category: 'MAINTENANCE',
    targetDepartment: 'MAINTENANCE',
    priority: 'URGENT',
    body: '🚨 URGENT: Maintenance needed in Room {{roomNumber}}. Issue: {{issue}}. Guest is {{guestStatus}}. Please respond immediately.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 203' },
      { key: 'issue', label: 'Issue Description', type: 'text', required: true, placeholder: 'e.g. Plumbing leak' },
      { key: 'guestStatus', label: 'Guest Status', type: 'text', required: true, placeholder: 'e.g. in room' },
    ],
    requiresAcknowledgment: true,
    tags: ['urgent', 'maintenance', 'emergency'],
  },
  {
    name: 'Maintenance Completed',
    category: 'MAINTENANCE',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: '✅ Maintenance completed for Room {{roomNumber}}. Work performed: {{workDone}}. Room is now {{status}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 305' },
      { key: 'workDone', label: 'Work Performed', type: 'text', required: true, placeholder: 'e.g. Fixed AC unit' },
      { key: 'status', label: 'Room Status', type: 'text', required: true, defaultValue: 'ready for use' },
    ],
    requiresAcknowledgment: false,
    tags: ['maintenance', 'completed', 'room-ready'],
  },
  {
    name: 'Preventive Maintenance Schedule',
    category: 'MAINTENANCE',
    targetDepartment: 'MAINTENANCE',
    priority: 'NORMAL',
    body: 'Preventive maintenance scheduled for Room {{roomNumber}} on {{maintenanceDate}}. Work: {{workDescription}}. Duration: {{duration}} hours. Room must be vacant.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 418' },
      { key: 'maintenanceDate', label: 'Maintenance Date', type: 'date', required: true, placeholder: 'e.g. Next Tuesday' },
      { key: 'workDescription', label: 'Work Description', type: 'text', required: true, placeholder: 'e.g. HVAC filter replacement' },
      { key: 'duration', label: 'Duration (hours)', type: 'number', required: false, defaultValue: '2' },
    ],
    requiresAcknowledgment: false,
    tags: ['preventive', 'maintenance', 'scheduling'],
  },
  {
    name: 'Equipment Malfunction',
    category: 'MAINTENANCE',
    targetDepartment: 'MAINTENANCE',
    priority: 'HIGH',
    body: 'Equipment malfunction: {{equipment}} in {{location}}. Issue: {{issue}}. Impact: {{impact}}. Priority repair needed.',
    variables: [
      { key: 'equipment', label: 'Equipment', type: 'text', required: true, placeholder: 'e.g. Ice machine' },
      { key: 'location', label: 'Location', type: 'text', required: true, placeholder: 'e.g. 3rd floor hallway' },
      { key: 'issue', label: 'Issue', type: 'text', required: true, placeholder: 'e.g. Not producing ice' },
      { key: 'impact', label: 'Impact', type: 'text', required: true, placeholder: 'e.g. Affects all 3rd floor guests' },
    ],
    requiresAcknowledgment: true,
    tags: ['equipment', 'malfunction', 'priority'],
  },
  {
    name: 'Safety Hazard Identified',
    category: 'MAINTENANCE',
    targetDepartment: 'MAINTENANCE',
    priority: 'URGENT',
    body: '⚠️ SAFETY HAZARD: {{hazardDescription}} at {{location}}. Immediate action required. Area {{areaStatus}}.',
    variables: [
      { key: 'hazardDescription', label: 'Hazard Description', type: 'text', required: true, placeholder: 'e.g. Wet floor, broken railing' },
      { key: 'location', label: 'Location', type: 'text', required: true, placeholder: 'e.g. Main lobby entrance' },
      { key: 'areaStatus', label: 'Area Status', type: 'text', required: true, placeholder: 'e.g. cordoned off' },
    ],
    requiresAcknowledgment: true,
    tags: ['safety', 'urgent', 'hazard'],
  },
  {
    name: 'Shift Handover - Front Desk',
    category: 'SHIFT_HANDOVER',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: 'Front Desk Shift Handover:\n\n📋 Arrivals today: {{arrivals}}\n📤 Departures pending: {{departures}}\n⚠️ Issues to note: {{issues}}\n💰 Cash drawer: {{cashStatus}}\n\nAdditional notes: {{notes}}',
    variables: [
      { key: 'arrivals', label: 'Arrivals Count', type: 'number', required: true, defaultValue: '0' },
      { key: 'departures', label: 'Pending Departures', type: 'number', required: true, defaultValue: '0' },
      { key: 'issues', label: 'Issues to Note', type: 'text', required: false, defaultValue: 'None' },
      { key: 'cashStatus', label: 'Cash Drawer Status', type: 'text', required: true, defaultValue: 'Balanced' },
      { key: 'notes', label: 'Additional Notes', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: true,
    tags: ['handover', 'shift-change', 'front-desk'],
  },
  {
    name: 'Shift Handover - Housekeeping',
    category: 'SHIFT_HANDOVER',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Housekeeping Shift Handover:\n\n✅ Rooms cleaned: {{cleaned}}\n🔄 Rooms in progress: {{inProgress}}\n🧹 Priority rooms for next shift: {{priority}}\n🛠️ Supplies needed: {{supplies}}\n\nNotes: {{notes}}',
    variables: [
      { key: 'cleaned', label: 'Rooms Cleaned', type: 'number', required: true, defaultValue: '0' },
      { key: 'inProgress', label: 'Rooms In Progress', type: 'text', required: false, defaultValue: 'None' },
      { key: 'priority', label: 'Priority Rooms', type: 'text', required: false, defaultValue: 'None' },
      { key: 'supplies', label: 'Supplies Needed', type: 'text', required: false, defaultValue: 'Stocked' },
      { key: 'notes', label: 'Additional Notes', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: true,
    tags: ['handover', 'shift-change', 'housekeeping'],
  },
  {
    name: 'Shift Handover - Maintenance',
    category: 'SHIFT_HANDOVER',
    targetDepartment: 'MAINTENANCE',
    priority: 'NORMAL',
    body: 'Maintenance Shift Handover:\n\n🔧 Work orders completed: {{completed}}\n⏳ Work orders pending: {{pending}}\n🚨 Urgent items: {{urgent}}\n🛠️ Equipment status: {{equipmentStatus}}\n\nNotes: {{notes}}',
    variables: [
      { key: 'completed', label: 'Completed Work Orders', type: 'number', required: true, defaultValue: '0' },
      { key: 'pending', label: 'Pending Work Orders', type: 'text', required: false, defaultValue: 'None' },
      { key: 'urgent', label: 'Urgent Items', type: 'text', required: false, defaultValue: 'None' },
      { key: 'equipmentStatus', label: 'Equipment Status', type: 'text', required: false, defaultValue: 'All operational' },
      { key: 'notes', label: 'Additional Notes', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: true,
    tags: ['handover', 'shift-change', 'maintenance'],
  },
  {
    name: 'Guest Complaint - Immediate Action',
    category: 'URGENT_ALERT',
    targetDepartment: 'MANAGEMENT',
    priority: 'URGENT',
    body: '🚨 Guest complaint requiring immediate attention!\n\nGuest: {{guestName}}\nRoom: {{roomNumber}}\nComplaint: {{complaint}}\nCurrent status: {{status}}\n\nPlease address immediately.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 210' },
      { key: 'complaint', label: 'Complaint Details', type: 'text', required: true, placeholder: 'Describe the issue' },
      { key: 'status', label: 'Current Status', type: 'text', required: true, placeholder: 'e.g. Guest waiting at desk' },
    ],
    requiresAcknowledgment: true,
    tags: ['urgent', 'complaint', 'management'],
  },
  {
    name: 'Security Incident',
    category: 'URGENT_ALERT',
    targetDepartment: 'MANAGEMENT',
    priority: 'URGENT',
    body: '🚨 SECURITY INCIDENT: {{incidentType}} at {{location}}. Time: {{time}}. Status: {{status}}. {{actionTaken}}',
    variables: [
      { key: 'incidentType', label: 'Incident Type', type: 'text', required: true, placeholder: 'e.g. Unauthorized access' },
      { key: 'location', label: 'Location', type: 'text', required: true, placeholder: 'e.g. Pool area' },
      { key: 'time', label: 'Time', type: 'time', required: true, placeholder: 'e.g. 11:30 PM' },
      { key: 'status', label: 'Status', type: 'text', required: true, placeholder: 'e.g. Resolved' },
      { key: 'actionTaken', label: 'Action Taken', type: 'text', required: true, placeholder: 'e.g. Security contacted' },
    ],
    requiresAcknowledgment: true,
    tags: ['security', 'urgent', 'incident'],
  },
  {
    name: 'Medical Emergency',
    category: 'URGENT_ALERT',
    targetDepartment: 'MANAGEMENT',
    priority: 'URGENT',
    body: '🚨 MEDICAL EMERGENCY - Room {{roomNumber}}. Situation: {{situation}}. Emergency services: {{emergencyStatus}}. Location: {{location}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 325' },
      { key: 'situation', label: 'Situation', type: 'text', required: true, placeholder: 'e.g. Guest fell' },
      { key: 'emergencyStatus', label: 'Emergency Services Status', type: 'text', required: true, placeholder: 'e.g. Called, ETA 5 min' },
      { key: 'location', label: 'Exact Location', type: 'text', required: true, placeholder: 'e.g. In room bathroom' },
    ],
    requiresAcknowledgment: true,
    tags: ['medical', 'emergency', 'urgent'],
  },
  {
    name: 'Fire Alarm Activation',
    category: 'URGENT_ALERT',
    targetDepartment: 'ALL',
    priority: 'URGENT',
    body: '🔥 FIRE ALARM ACTIVATED - {{location}}. Type: {{alarmType}}. Guests evacuating: {{evacuationStatus}}. Fire department: {{fireDeptStatus}}.',
    variables: [
      { key: 'location', label: 'Location', type: 'text', required: true, placeholder: 'e.g. 4th floor, west wing' },
      { key: 'alarmType', label: 'Alarm Type', type: 'text', required: true, placeholder: 'e.g. Smoke detector' },
      { key: 'evacuationStatus', label: 'Evacuation Status', type: 'text', required: true, placeholder: 'e.g. In progress' },
      { key: 'fireDeptStatus', label: 'Fire Department Status', type: 'text', required: true, placeholder: 'e.g. Notified, en route' },
    ],
    requiresAcknowledgment: true,
    tags: ['fire', 'emergency', 'evacuation'],
  },
  {
    name: 'Early Check-In Request',
    category: 'GUEST_REQUEST',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'HIGH',
    body: 'Early check-in request for {{guestName}}. Arrival time: {{arrivalTime}}. Assigned room: {{roomNumber}}. Current status: {{currentStatus}}. Can we accommodate?',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'arrivalTime', label: 'Arrival Time', type: 'time', required: true, placeholder: 'e.g. 10:00 AM' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 105' },
      { key: 'currentStatus', label: 'Current Room Status', type: 'text', required: true, placeholder: 'e.g. Dirty' },
    ],
    requiresAcknowledgment: true,
    tags: ['early-check-in', 'guest-request', 'priority'],
  },
  {
    name: 'Late Check-Out Approved',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Late check-out approved for {{guestName}} in Room {{roomNumber}}. New departure time: {{departureTime}}. Please adjust cleaning schedule accordingly.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 308' },
      { key: 'departureTime', label: 'New Departure Time', type: 'time', required: true, placeholder: 'e.g. 2:00 PM' },
    ],
    requiresAcknowledgment: false,
    tags: ['late-checkout', 'scheduling', 'housekeeping'],
  },
  {
    name: 'Lost and Found Item',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: 'Item found in Room {{roomNumber}}: {{itemDescription}}. Last guest: {{guestName}}. Item is being held at front desk. Log number: {{logNumber}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 412' },
      { key: 'itemDescription', label: 'Item Description', type: 'text', required: true, placeholder: 'e.g. Black phone charger' },
      { key: 'guestName', label: 'Previous Guest', type: 'guest', required: false, placeholder: 'Previous guest name' },
      { key: 'logNumber', label: 'Log Number', type: 'text', required: false, defaultValue: 'Auto-generated' },
    ],
    requiresAcknowledgment: false,
    tags: ['lost-and-found', 'guest-property'],
  },
  {
    name: 'Group Check-In Alert',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'FRONT_DESK',
    priority: 'HIGH',
    body: 'Group check-in scheduled: {{groupName}} - {{numberOfGuests}} guests arriving at {{arrivalTime}}. Rooms assigned: {{roomNumbers}}. Lead contact: {{contactName}}.',
    variables: [
      { key: 'groupName', label: 'Group Name', type: 'text', required: true, placeholder: 'e.g. Smith Wedding Party' },
      { key: 'numberOfGuests', label: 'Number of Guests', type: 'number', required: true, placeholder: 'e.g. 15' },
      { key: 'arrivalTime', label: 'Arrival Time', type: 'time', required: true, placeholder: 'e.g. 4:00 PM' },
      { key: 'roomNumbers', label: 'Room Numbers', type: 'text', required: true, placeholder: 'Room list or range' },
      { key: 'contactName', label: 'Lead Contact', type: 'guest', required: true, placeholder: 'Lead guest name' },
    ],
    requiresAcknowledgment: true,
    tags: ['group', 'check-in', 'scheduling'],
  },
  {
    name: 'Amenity Restock Needed',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Amenity restock needed: {{items}}. Current inventory: {{currentLevel}}. Please restock by {{deadline}}.',
    variables: [
      { key: 'items', label: 'Items Needed', type: 'text', required: true, placeholder: 'e.g. Toiletries, towels' },
      { key: 'currentLevel', label: 'Current Inventory', type: 'text', required: false, defaultValue: 'Low' },
      { key: 'deadline', label: 'Restock By', type: 'date', required: false, defaultValue: 'End of day' },
    ],
    requiresAcknowledgment: false,
    tags: ['supplies', 'inventory', 'housekeeping'],
  },
  {
    name: 'No Show - Room Available',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: 'No-show for reservation {{confirmationNumber}}. Guest: {{guestName}}. Room {{roomNumber}} is now available for re-assignment.',
    variables: [
      { key: 'confirmationNumber', label: 'Confirmation Number', type: 'text', required: true, placeholder: 'e.g. ABC123' },
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 115' },
    ],
    requiresAcknowledgment: false,
    tags: ['no-show', 'availability', 'front-desk'],
  },
  {
    name: 'Overbooked - Need Solution',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'MANAGEMENT',
    priority: 'URGENT',
    body: '⚠️ OVERBOOKING SITUATION: {{numberOfBookings}} guests, {{availableRooms}} rooms available. Date: {{date}}. Need walk/upgrade solution immediately.',
    variables: [
      { key: 'numberOfBookings', label: 'Number of Bookings', type: 'number', required: true, placeholder: 'e.g. 5' },
      { key: 'availableRooms', label: 'Available Rooms', type: 'number', required: true, placeholder: 'e.g. 3' },
      { key: 'date', label: 'Date', type: 'date', required: true, placeholder: 'Today' },
    ],
    requiresAcknowledgment: true,
    tags: ['overbooking', 'urgent', 'management'],
  },
  {
    name: 'Minibar Restock',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Minibar restock needed for Room {{roomNumber}}. Items consumed: {{itemsConsumed}}. Standard restock plus: {{additionalItems}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 225' },
      { key: 'itemsConsumed', label: 'Items Consumed', type: 'text', required: true, placeholder: 'e.g. 2 waters, 1 soda' },
      { key: 'additionalItems', label: 'Additional Items', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: false,
    tags: ['minibar', 'restock', 'housekeeping'],
  },
  {
    name: 'Laundry Service Request',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'HOUSEKEEPING',
    priority: 'NORMAL',
    body: 'Laundry service request from Room {{roomNumber}} - {{guestName}}. Items: {{items}}. Return by: {{returnTime}}. Express: {{isExpress}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 318' },
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'items', label: 'Items', type: 'text', required: true, placeholder: 'e.g. 3 shirts, 2 pants' },
      { key: 'returnTime', label: 'Return By', type: 'time', required: true, placeholder: 'e.g. 6:00 PM' },
      { key: 'isExpress', label: 'Express Service', type: 'text', required: false, defaultValue: 'No' },
    ],
    requiresAcknowledgment: false,
    tags: ['laundry', 'guest-service', 'housekeeping'],
  },
  {
    name: 'Parking Assistance Needed',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'FRONT_DESK',
    priority: 'NORMAL',
    body: 'Valet parking needed for {{guestName}} - Room {{roomNumber}}. Vehicle: {{vehicleDescription}}. Special instructions: {{instructions}}.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 510' },
      { key: 'vehicleDescription', label: 'Vehicle Description', type: 'text', required: true, placeholder: 'e.g. Black Tesla Model S' },
      { key: 'instructions', label: 'Special Instructions', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: false,
    tags: ['valet', 'parking', 'guest-service'],
  },
  {
    name: 'Payment Issue Alert',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'CASHIER',
    priority: 'HIGH',
    body: 'Payment issue for Room {{roomNumber}} - {{guestName}}. Issue: {{issue}}. Amount: {{amount}}. Action needed: {{actionNeeded}}.',
    variables: [
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 407' },
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'issue', label: 'Issue', type: 'text', required: true, placeholder: 'e.g. Card declined' },
      { key: 'amount', label: 'Amount', type: 'text', required: true, placeholder: 'e.g. $450.00' },
      { key: 'actionNeeded', label: 'Action Needed', type: 'text', required: true, placeholder: 'e.g. Contact guest for new payment' },
    ],
    requiresAcknowledgment: true,
    tags: ['payment', 'billing', 'cashier'],
  },
  {
    name: 'Extended Stay Notification',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'ALL',
    priority: 'NORMAL',
    body: 'Extended stay confirmed: {{guestName}} - Room {{roomNumber}}. Original checkout: {{originalCheckout}}. New checkout: {{newCheckout}}. Total nights: {{totalNights}}.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 302' },
      { key: 'originalCheckout', label: 'Original Checkout', type: 'date', required: true, placeholder: 'e.g. Tomorrow' },
      { key: 'newCheckout', label: 'New Checkout', type: 'date', required: true, placeholder: 'e.g. Next week' },
      { key: 'totalNights', label: 'Total Nights', type: 'number', required: true, placeholder: 'e.g. 7' },
    ],
    requiresAcknowledgment: false,
    tags: ['extended-stay', 'booking', 'front-desk'],
  },
  {
    name: 'Cancellation - Same Day',
    category: 'DAILY_OPERATIONS',
    targetDepartment: 'FRONT_DESK',
    priority: 'HIGH',
    body: 'Same-day cancellation: {{guestName}} - Room {{roomNumber}}. Confirmation: {{confirmationNumber}}. Room now available. Cancellation fee: {{fee}}.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 218' },
      { key: 'confirmationNumber', label: 'Confirmation Number', type: 'text', required: true, placeholder: 'e.g. XYZ789' },
      { key: 'fee', label: 'Cancellation Fee', type: 'text', required: false, defaultValue: 'None' },
    ],
    requiresAcknowledgment: false,
    tags: ['cancellation', 'availability', 'front-desk'],
  },
  {
    name: 'Birthday/Anniversary Alert',
    category: 'GUEST_REQUEST',
    targetDepartment: 'ALL',
    priority: 'NORMAL',
    body: '🎉 Special occasion: {{guestName}} - Room {{roomNumber}} celebrating {{occasion}}. Arranged: {{arrangements}}. Deliver at: {{deliveryTime}}.',
    variables: [
      { key: 'guestName', label: 'Guest Name', type: 'guest', required: true, placeholder: 'Guest full name' },
      { key: 'roomNumber', label: 'Room Number', type: 'room', required: true, placeholder: 'e.g. 425' },
      { key: 'occasion', label: 'Occasion', type: 'text', required: true, placeholder: 'e.g. Birthday' },
      { key: 'arrangements', label: 'Arrangements', type: 'text', required: true, placeholder: 'e.g. Champagne & cake' },
      { key: 'deliveryTime', label: 'Delivery Time', type: 'time', required: false, defaultValue: 'Upon check-in' },
    ],
    requiresAcknowledgment: false,
    tags: ['celebration', 'special-occasion', 'guest-service'],
  },
]

export function createTemplateId(): string {
  return `tmpl-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
}

export function replaceTemplateVariables(template: string, values: Record<string, string>): string {
  let result = template
  Object.entries(values).forEach(([key, value]) => {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value)
  })
  return result
}

export function extractTemplateVariables(template: string): string[] {
  const matches = template.match(/{{([^}]+)}}/g)
  if (!matches) return []
  return matches.map(m => m.replace(/{{|}}/g, ''))
}

export function getTemplatesByCategory(templates: StaffMessageTemplate[], category: StaffTemplateCategory): StaffMessageTemplate[] {
  return templates.filter(t => t.category === category)
}

export function getTemplatesByDepartment(templates: StaffMessageTemplate[], department: StaffDepartment): StaffMessageTemplate[] {
  return templates.filter(t => t.targetDepartment === department || t.targetDepartment === 'ALL')
}

export function getFavoriteTemplates(templates: StaffMessageTemplate[]): StaffMessageTemplate[] {
  return templates.filter(t => t.isFavorite).sort((a, b) => b.usageCount - a.usageCount)
}

export function getMostUsedTemplates(templates: StaffMessageTemplate[], limit: number = 5): StaffMessageTemplate[] {
  return [...templates].sort((a, b) => b.usageCount - a.usageCount).slice(0, limit)
}

export const TEMPLATE_CATEGORIES: { value: StaffTemplateCategory; label: string; icon: string }[] = [
  { value: 'ROOM_STATUS', label: 'Room Status', icon: 'bed' },
  { value: 'GUEST_REQUEST', label: 'Guest Requests', icon: 'user' },
  { value: 'MAINTENANCE', label: 'Maintenance', icon: 'wrench' },
  { value: 'SHIFT_HANDOVER', label: 'Shift Handover', icon: 'arrows-clockwise' },
  { value: 'URGENT_ALERT', label: 'Urgent Alerts', icon: 'warning' },
  { value: 'DAILY_OPERATIONS', label: 'Daily Operations', icon: 'calendar' },
  { value: 'CUSTOM', label: 'Custom', icon: 'pencil' },
]
