"""phase34 auth public booking

Revision ID: 22fbc1b3bf47
Revises: 20260307_01
Create Date: 2026-03-07 13:30:45.842986

"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '22fbc1b3bf47'
down_revision = '20260307_01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('entity_table', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log_actor_created_at', 'activity_log', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_activity_log_event_created_at', 'activity_log', ['event_type', 'created_at'], unique=False)
    op.create_table('auth_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempted_identifier', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=40), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("failure_reason IS NULL OR failure_reason IN ('invalid_credentials', 'locked', 'disabled', 'inactive', 'mfa_required', 'mfa_failed', 'reset_rate_limited')", name='ck_auth_attempts_failure_reason'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_attempts_identifier_attempted_at', 'auth_attempts', ['attempted_identifier', 'attempted_at'], unique=False)
    op.create_index('ix_auth_attempts_ip_attempted_at', 'auth_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index('ix_auth_attempts_user_attempted_at', 'auth_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_table('mfa_factors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('factor_type', sa.String(length=40), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("factor_type IN ('totp')", name='ck_mfa_factors_factor_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mfa_factors_user_id', 'mfa_factors', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_password_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_password_history_user_id', 'user_password_history', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('selector', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selector')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('mfa_recovery_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mfa_factor_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mfa_factor_id'], ['mfa_factors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index('ix_mfa_recovery_codes_factor_id', 'mfa_recovery_codes', ['mfa_factor_id'], unique=False)
    op.create_table('cancellation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('request_code', sa.String(length=24), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('requester_contact_hash', sa.String(length=255), nullable=False),
    sa.Column('requester_contact_hint', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.CheckConstraint("status IN ('submitted', 'auto_processed', 'needs_review', 'approved', 'declined')", name='ck_cancellation_requests_status'),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    op.create_index('ix_cancellation_requests_booking_reference', 'cancellation_requests', ['booking_reference'], unique=False)
    op.create_index('ix_cancellation_requests_status_requested', 'cancellation_requests', ['status', 'requested_at'], unique=False)
    op.create_table('email_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_type', sa.String(length=80), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("language IN ('th', 'en', 'zh-Hans')", name='ck_email_outbox_language'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name='ck_email_outbox_status'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_email_outbox_status_created', 'email_outbox', ['status', 'created_at'], unique=False)
    op.create_table('modification_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('request_code', sa.String(length=24), nullable=False),
    sa.Column('requested_changes', sa.JSON(), nullable=False),
    sa.Column('requester_contact_hash', sa.String(length=255), nullable=False),
    sa.Column('requester_contact_hint', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.CheckConstraint("status IN ('submitted', 'reviewed', 'approved', 'declined')", name='ck_modification_requests_status'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    op.create_index('ix_modification_requests_reservation_id', 'modification_requests', ['reservation_id'], unique=False)
    op.create_index('ix_modification_requests_status_requested', 'modification_requests', ['status', 'requested_at'], unique=False)
    op.create_table('reservation_holds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hold_code', sa.String(length=24), nullable=False),
    sa.Column('room_type_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_room_id', sa.Uuid(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('extra_guests', sa.Integer(), nullable=False),
    sa.Column('source_channel', sa.String(length=40), nullable=False),
    sa.Column('booking_language', sa.String(length=20), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('quoted_room_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quoted_tax_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quoted_grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('converted_reservation_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("booking_language IN ('th', 'en', 'zh-Hans')", name='ck_reservation_holds_booking_language'),
    sa.CheckConstraint("source_channel IN ('direct_web', 'google_business', 'facebook', 'line', 'whatsapp', 'qr', 'referral', 'admin_manual')", name='ck_reservation_holds_source_channel'),
    sa.CheckConstraint("status IN ('active', 'converted', 'expired', 'released')", name='ck_reservation_holds_status'),
    sa.CheckConstraint('adults >= 1', name='ck_reservation_holds_adults'),
    sa.CheckConstraint('check_in_date < check_out_date', name='ck_reservation_holds_dates'),
    sa.CheckConstraint('children >= 0', name='ck_reservation_holds_children'),
    sa.CheckConstraint('extra_guests >= 0', name='ck_reservation_holds_extra_guests'),
    sa.ForeignKeyConstraint(['assigned_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hold_code'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_reservation_holds_dates', 'reservation_holds', ['check_in_date', 'check_out_date'], unique=False)
    op.create_index('ix_reservation_holds_guest_email', 'reservation_holds', ['guest_email'], unique=False)
    op.create_index('ix_reservation_holds_status_expires_at', 'reservation_holds', ['status', 'expires_at'], unique=False)
    op.create_table('reservation_review_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('deposit_state', sa.String(length=40), nullable=True),
    sa.Column('flagged_duplicate_suspected', sa.Boolean(), nullable=False),
    sa.Column('special_requests_present', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("review_status IN ('new', 'reviewed', 'needs_follow_up', 'issue_flagged', 'resolved')", name='ck_reservation_review_queue_status'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index('ix_reservation_review_queue_status_created', 'reservation_review_queue', ['review_status', 'created_at'], unique=False)
    op.create_table('staff_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('new', 'read')", name='ck_staff_notifications_status'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_notifications_status_created', 'staff_notifications', ['status', 'created_at'], unique=False)
    with op.batch_alter_table('inventory_days', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('hold_id', sa.Uuid(), nullable=True))
        batch_op.create_index('ix_inventory_days_hold_id', ['hold_id'], unique=False)
        batch_op.create_foreign_key('fk_inventory_days_hold_id_reservation_holds', 'reservation_holds', ['hold_id'], ['id'], ondelete='SET NULL')
        batch_op.create_check_constraint('ck_inventory_days_hold_requires_held_status', "(hold_id IS NULL) OR availability_status = 'held'")
    with op.batch_alter_table('reservations', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('created_from_public_booking_flow', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('booking_language', sa.String(length=20), nullable=False, server_default='th'))
        batch_op.add_column(sa.Column('source_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_suspected', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('terms_version', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('public_confirmation_token', sa.String(length=120), nullable=True))
        batch_op.drop_index(op.f('ix_reservations_arrivals'))
        batch_op.drop_index(op.f('ix_reservations_departures'))
        batch_op.create_unique_constraint('uq_reservations_public_confirmation_token', ['public_confirmation_token'])
        batch_op.create_check_constraint('ck_reservations_booking_language', "booking_language IN ('th', 'en', 'zh-Hans')")
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    with op.batch_alter_table('users', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('account_state', sa.String(length=40), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('force_password_reset', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('mfa_required', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute(
        """
        UPDATE users
        SET username = lower(substr(email, 1, CASE WHEN instr(email, '@') > 0 THEN instr(email, '@') - 1 ELSE length(email) END))
        WHERE username IS NULL
        """
    )
    with op.batch_alter_table('users', recreate='always') as batch_op:
        batch_op.create_index('ix_users_active_username', ['username'], unique=False)
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.create_check_constraint('ck_users_account_state', "account_state IN ('invited', 'active', 'password_reset_required', 'locked', 'disabled')")
        batch_op.create_check_constraint('ck_users_failed_login_count', 'failed_login_count >= 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', recreate='always') as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_index('ix_users_active_username')
        batch_op.drop_constraint('ck_users_failed_login_count', type_='check')
        batch_op.drop_constraint('ck_users_account_state', type_='check')
        batch_op.drop_column('mfa_required')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('force_password_reset')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('last_failed_login_at')
        batch_op.drop_column('failed_login_count')
        batch_op.drop_column('account_state')
        batch_op.drop_column('username')
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    with op.batch_alter_table('reservations', recreate='always') as batch_op:
        batch_op.drop_constraint('uq_reservations_public_confirmation_token', type_='unique')
        batch_op.drop_constraint('ck_reservations_booking_language', type_='check')
        batch_op.create_index(op.f('ix_reservations_departures'), ['check_out_date', 'current_status'], unique=False)
        batch_op.create_index(op.f('ix_reservations_arrivals'), ['check_in_date', 'current_status'], unique=False)
        batch_op.drop_column('public_confirmation_token')
        batch_op.drop_column('terms_version')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('duplicate_suspected')
        batch_op.drop_column('source_metadata')
        batch_op.drop_column('booking_language')
        batch_op.drop_column('created_from_public_booking_flow')
    with op.batch_alter_table('inventory_days', recreate='always') as batch_op:
        batch_op.drop_constraint('ck_inventory_days_hold_requires_held_status', type_='check')
        batch_op.drop_constraint('fk_inventory_days_hold_id_reservation_holds', type_='foreignkey')
        batch_op.drop_index('ix_inventory_days_hold_id')
        batch_op.drop_column('hold_id')
    op.drop_index('ix_staff_notifications_status_created', table_name='staff_notifications')
    op.drop_table('staff_notifications')
    op.drop_index('ix_reservation_review_queue_status_created', table_name='reservation_review_queue')
    op.drop_table('reservation_review_queue')
    op.drop_index('ix_reservation_holds_status_expires_at', table_name='reservation_holds')
    op.drop_index('ix_reservation_holds_guest_email', table_name='reservation_holds')
    op.drop_index('ix_reservation_holds_dates', table_name='reservation_holds')
    op.drop_table('reservation_holds')
    op.drop_index('ix_modification_requests_status_requested', table_name='modification_requests')
    op.drop_index('ix_modification_requests_reservation_id', table_name='modification_requests')
    op.drop_table('modification_requests')
    op.drop_index('ix_email_outbox_status_created', table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_index('ix_cancellation_requests_status_requested', table_name='cancellation_requests')
    op.drop_index('ix_cancellation_requests_booking_reference', table_name='cancellation_requests')
    op.drop_table('cancellation_requests')
    op.drop_index('ix_mfa_recovery_codes_factor_id', table_name='mfa_recovery_codes')
    op.drop_table('mfa_recovery_codes')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_password_history_user_id', table_name='user_password_history')
    op.drop_table('user_password_history')
    op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_expires_at', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_mfa_factors_user_id', table_name='mfa_factors')
    op.drop_table('mfa_factors')
    op.drop_index('ix_auth_attempts_user_attempted_at', table_name='auth_attempts')
    op.drop_index('ix_auth_attempts_ip_attempted_at', table_name='auth_attempts')
    op.drop_index('ix_auth_attempts_identifier_attempted_at', table_name='auth_attempts')
    op.drop_table('auth_attempts')
    op.drop_index('ix_activity_log_event_created_at', table_name='activity_log')
    op.drop_index('ix_activity_log_actor_created_at', table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
