ALTER TYPE "RoomStatus" ADD VALUE IF NOT EXISTS 'CLEANING';
ALTER TYPE "RoomStatus" ADD VALUE IF NOT EXISTS 'INSPECTED';
ALTER TYPE "RoomStatus" ADD VALUE IF NOT EXISTS 'OCCUPIED_CLEAN';

ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'HOLD';

ALTER TABLE "Reservation"
  ADD CONSTRAINT "Reservation_assignedRoomId_fkey"
  FOREIGN KEY ("assignedRoomId") REFERENCES "Room"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
